version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Latest Node.js
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Pre-build phase..."
  build:
    commands:
      - echo "Building app..."
      - npm run build  # Or npm install if no build script
  post_build:
    commands:
      - echo "Build complete!"

artifacts:
  files:
    - '**/*'  # Include all files for deploy
  discard-paths: no